### ISSUE TITLE
SpiffyTitles: Additional information about coub links

### ISSUE THREAD

**Issue by iyx** [prgmrbill/limnoria-plugins#54]
Coub.com - service for displaying short looped videos.

Info: http://coub.com/dev/docs/Coub+API/Coubs

Example: http://coub.com/view/6oztc --> http://coub.com/api/v2/coubs/6oztc

I'm in particular interested in being able to display {{title}} {{channel_title}} {{views_count}} {{likes_count}} {{recoubs_count}}

:)

**Comment by prgmrbill** [comment]
Looks like fun! Are there any other details you'd like to see?

**Comment by prgmrbill** [comment]
Please open a new issue for further enhancements to this feature. Thanks!
